#!/Users/shashwatraghuvanshi/miniconda3/bin/python3

"""
The objective of this script is to press the function key every 5 mins to avoid locking of pc
"""

import pyautogui

while True:
	pyautogui.press('fn', interval=60*5-1)

# # Test
# print('begin')
# pyautogui.press('shift', interval=2)
# pyautogui.press(['fn'], presses=5, interval=2)
# # pyautogui.press(['fn', 'del'], presses=5, interval=2)
# # test behaviour by keeping cursor as |1234567.. and see the nos disappear
# print('done')
